
project_id = "bmyrltwtvpfrbdiwoqem"

[api]
enabled = true

[db]
enabled = true

[realtime]
enabled = true

[storage]
enabled = true

[analytics]
enabled = false

[functions]
enabled = true

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.subscription-details]
verify_jwt = true
