
project_id = "bmyrltwtvpfrbdiwoqem"
[api]
port = 54321
schemes = ["http", "https"]
[api.cors]
enabled = true
[db]
port = 54322
[db.pooler]
enabled = false
port = 54329
[realtime]
enabled = true
[studio]
enabled = true
port = 54323
[storage]
enabled = true
[inbucket]
enabled = true
port = 54324
[functions]
[functions.stripe-webhook]
verify_jwt = false
