// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmyrltwtvpfrbdiwoqem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJteXJsdHd0dnBmcmJkaXdvcWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NjQwMDQsImV4cCI6MjA1NzE0MDAwNH0.FHWGZ-w2sa6hP0EHZYwuCF5e8st0LrQxbWqMNTJ5qg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);